### PR TITLE
Fix/works on windows too

### PR DESCRIPTION
**Pull request by andrewalderson**
This pr addresses issues causing Mookme to fail on Windows.
It mainly removes Linux only commands.

It will close https://github.com/Escape-Technologies/mookme/issues/83, https://github.com/Escape-Technologies/mookme/issues/84

### CODE REVIEW

**Comment by LMaxence** [comment]
Thanks ! I'll merge it asap and release on the beta channel

**Comment by LMaxence** [comment]
Thanks for your contribution ! It is published in the beta channel and can be retrieved using `npm i --save-dev @escape.tech/mookme@2.2.0-beta.3` :)

**Comment by andrewalderson** [comment]
I have tested this out but have run into a few more issues specifically with the beta 2 branch. It all works on Linux (I tested it by running it in WSL with Ubuntu). On Windows the hooks just don't run. This repo uses a beta 1 version in the root package.json so I didn't see these issues when I was implementing these changes. I created a new repo to test the ```2.2.0-beta.3``` version and ```npx mookme init``` works correctly and sets the file mode but when doing a commit with that version the hooks don't run. If I switch to a beta 1 version in the package.json file then try to commit the hooks will run. Although I am still having some issues with certain commands. I am running everything in Powershell Core which is cross-platform and aliases commands like ```cat```. I am getting errors about ```npx``` not being found for my ```commit-msg``` hook even though I can do an ```npx --help``` from the same directory and all of the hooks in the ```.git``` directory also use ```npx```.

I have also noticed that the prompts when running ```npx mookme init``` are missing with the beta 2 version. It doesn't set the ```packagesPath``` or ```packages``` array in the ```mookme.json``` file on Windows or Linux. I had to add them manually.

I think that something changed between beta 1 and beta 2 to cause this. I will continue looking into this but it may take a bit of time. I will file another issue when I have more info.

**Comment by LMaxence** [comment]
> I have also noticed that the prompts when running npx mookme init are missing with the beta 2 version. It doesn't set the packagesPath or packages array in the mookme.json file on Windows or Linux. I had to add them manually.

That's because you don't need to set this in Mookme 2, I drastically simplified the setup. The tool automatically resolves folder with a .hooks/{hook-type}.json file in it !

**Comment by LMaxence** [comment]
I'll give a try also on a Windows setup on my side

**Comment by andrewalderson** [comment]
I did do a little preliminary investigation and it isn't the hooks that are failing. The ```npx run``` command is either failing silently or is not resolving the ```.hooks``` folders. I am continuing to investigate.

**Comment by andrewalderson** [comment]
After some more investigation is seems that the issue with the ```execSync``` calls in the ```GitToolkit``` class. Calling ```execSync('echo $(git diff --cached --name-only)').toString()``` in ```getStagedFiles()``` literally returns ```'$(git', 'diff', '--cached', '--name-only)\r'``` on Windows. If I just execute ```echo $(git diff --cached --name-only)``` in Powershell I get a list of the filenames that are staged and if I call it with ```toString()``` I get an object returned.

**Comment by andrewalderson** [comment]
Okay, so I have found the issue and I have it working on Linux and Windows. The issue exists in the ```GitToolkit``` class with all of the ```execSync``` calls that ```echo``` the git command output. I changed the ```getStagedFiles()``` method to 
```
  getStagedFiles(): string[] {
    debug(`getStagedFiles called`);
    const stagedFiles = execSync('git diff --cached --name-only').toString().split('\n');
    debug(`Retrieved the following files staged: ${stagedFiles}`);
    return stagedFiles;
  }
```
This works on both Linux and WIndows. Previously on Windows the ```echo``` just echoed the actual command and not the output of the command. In looking through the code for this class some of the methods call the git commands in a cross-platform way and some don't. They all need to be changed to not ```echo``` the git command and to split the output on the ```\n``` character.

I am still having issues with the ```commit-msg``` hook on Windows. The command ```"cat {args} | ./node_modules/@commitlint/cli/cli.js"``` is throws
```Hook of package global failed at step commit lint

'.' is not recognized as an internal or external command,
operable program or batch file.

stdout :
```
and the command ```"npx commitlint --edit"``` throws
```
Hook of package global failed at step commit lint

'"node"' is not recognized as an internal or external command,
operable program or batch file.

stdout :
```

I am still looking into this.

Also, another thing that needs to be addressed is that the tests only run on Linux. They need to be cross-platform in order to confirm the code works on Windows and Linux.

**Comment by andrewalderson** [comment]
I figured out the issues with the ```commit-msg``` hooks. I updated commitlint to the latest version (v 17) and now everything works on Linux and Windows. Also, can't use ```"cat {args} | ./node_modules/@commitlint/cli/cli.js"``` on Windows. It definitely won't work in ```cmd.exe``` because the ```cat``` command doesn't exist. On Powershell the ```cat``` command is mapped to a Powershell command but it doesn't like piping the output to the ```node_modules``` folder.  Have to use ```npx commitlint --edit``` to get the commit message to be linted.

I have to do a little more testing tomorrow and then I will create an issue and submit a pr. There is still a small issue with the git commands. When splitting the string to an array the last entry is an empty string and if I filter it out in some cases it stops working again. This isn't a major issue but it annoys me.

**Pull request merged**
