### PR TITLE
fix(mookme): add only changed files when using add and continue

### PR DESCRIPTION
**Pull request by LMaxence**
This fixes [issue 18](https://github.com/Escape-Technologies/mookme/issues/18)

I just go through the list of not-staged-initially-but-at-the-end files and add them one by one

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
Hmm, so actually I have a suggestion for this. What about instead of solving this issue directly, we just stashed un-added changes before running hooks so that the hooks don't see code that won't get committed? (And since everything would be stashed, adding all changed files is acceptable)

We could do this by [stashing twice](https://stackoverflow.com/a/39026300). Note we also will want to create two useless empty files, one added and one not added, to force stash to succeed even when no files are changed. So ultimately if it were written in bash, something like:

```bash
touch .empty-file-1 .empty-file-2
git add .empty-file-1
git stash
git stash -u
git stash pop stash@{1}
# Run hooks
git stash pop
for file in .empty-file-1 .empty-file-2; do
  if [ -f "$file" ]; then rm "$file"; done
done
``

**Comment by LMaxence** [comment]
Hey @MatthewScholefield ! @Julienlin has been working on a feature that is very very similar to what you describe [here](https://github.com/Escape-Technologies/mookme/pull/21) : 

However we're having a hard time to make it work for multiple reasons : 

- for reasons that I still cannot explain, git stash / no changes / unstash will create conflicts in some cases
We did find a way around this, but from what I've seen so far on the web, it is not a surprise. 
- We found a bug where some hook errors are forcing the exit of the process before running post-check actions, like unstash if needed. It is legit technical debt but will require to be fixed

**Comment by LMaxence** [comment]
I'm merging this, in the meantime we'll keep working on the stash feature :)

**Comment by Julienlin** [comment]
Hi @MatthewScholefield  !
We already have tested the stash method and it does not worked as expected. We often had conflicts at the end of hooks. We have found another a way by using stash with patches see #21. 
But the initial workflow of `mookme` does not go well with feature as of today.
There is an early exit that breaks the workflow in `processResults`.

**Pull request merged**
