### PR TITLE
feat(mookme): add noclear renderer

### LINKED ISSUE #94: Mookme erasing previous lines in terminal
I'm currently experimenting with Mookme in a monorepository on MacOS (12.3.1). I noticed that Mookme will remove lines from my terminal when running my commit-msg hook. 

I'm using Mookme in version 2.1.1 and tested it with iTerm2 as well as the Terminal app. For the shell I'm using zsh with the powerlevel10k theme. Though I also tested it using bash with the same result.

Steps I used to reproduce the issue:
- Init new git repository
- npx mookme init (enable commit-msg hook)
- created a subdirectory with a .hooks folder, a commit-msg.json and script

Directory:
```
❯ tree . -a
.
├── .gitignore
├── .hooks
│   ├── partials
│   │   └── .gitkeep
│   ├── pre-commit.json
│   └── shared
│       └── .gitkeep
├── .mookme.json
└── subdirectory
    ├── .hooks
    │   ├── commit-msg.json
    │   └── fail.sh
    └── testfile

5 directories, 8 files
```

commit-msg.json:
```
{
  "steps": [{
    "name": "Always fails",
    "command": ".hooks/fail.sh"
  }]
}
```

fail.sh:
```
#!/usr/bin/env bash
echo "always fails"
exit 1
```

When adding the file at `subdiretory/testfile` and running a git commit Mookme will output the hook status (which is set up to fail). Unfortunately it will remove some of the previous lines in the terminal as well.

I ran a `seq 100` to before running git commit to get a sense of what is missing. The `seq 100` will output all numbers from 1 to 100. After running git commit the terminal looks as follows:

```
{Prompt} /tmp/test_repository
❯ seq 100
1
2
3
4
5
6
7
8
9
10
11
12
13
  0 test
14

 Hooks : subdirectory  Error ×
→ Always fails > .hooks/fail.sh
❌ Error.

Hook of package subdirectory failed at step Always fails

stdout :

always fails


{Prompt} /tmp/test_repository 
❯
```

The `test` on line 16 here is the commit message.

What am I doing wrong? Is this a bug or simply a misconfiguration on my side? Also, is there a fallback mode that just prints the hook status line by line?

Please let me know if this might be a bug and I might be able to help debugging it in some way.

### PR DESCRIPTION
**Pull request by LMaxence**
Fixes #94 

[x] Made the rendering system extensible
[x] Added a renderer that won't clear the console
[x] Added an option in the `.mookme.json` to invoke this new renderer
[ ] Added documentation for this new option

image

### CODE REVIEW

**Comment by fabzo** [comment]
I tested it locally and it works for me. While not as pretty as the default renderer, it solves the issue with Mookme clearing the console. Thank you!

**Comment by LMaxence** [comment]
Great ! I'll merge this and deploy a new beta version today :)

**Comment by LMaxence** [comment]
Sorry for the delay ! `2.2.0-beta.6` is released and features this new logging option :)

**Comment by naseer036** [comment]
I want to use this feature. I have two hooks pre-commit and commit-msg, when the git commit is run then the pre-commit display is cleared. I think this feature is perfect for me. I didn't find the doc to use can you please help me out.

**Comment by LMaxence** [comment]
Hello ! Using the version mentioned above, `2.2.0-beta.6`, you will need to alter your mookme config file `.mookme.json` (located at the root of the repository) like so:

```json
{
  // ... the rest of the configuration
  "noClearRenderer": true
}
```

Regarding having this feature properly documented and deployed, summer time got me really, really, late on this but I will come up with something during next week. If it doesn't match your time table, feel free to update the docs :)

**Pull request merged**
